package cardoil.backend.enums;

public enum CodeErreurRecharge {
    ERR_INVALID_PHONE,
    ERR_INVALID_AMOUNT,
    ERR_DUPLICATE_REF,
    ERR_UNAUTHORIZED,
    ERR_PARTNER_INACTIVE,
    ERR_COMPANY_INACTIVE,
    ERR_CLIENT_NOT_FOUND,
    ERR_ACCOUNT_SUSPENDED,
    ERR_RATE_LIMIT,
    ERR_INTERNAL,
    ERR_UNAVAILABLE
}
